export const TIPOS_LAB = [
  // Hematología
  'Hematocrito',
  'Hemograma',
  'Perfil hemático',
  'Recuento Plaquetas',
  'Recuento de reticulocitos',
  'Hemograma control (pacientes fuera de hospitalización)',
  'Hemograma control (hospitalizados)',
  // Microbiología / Citología
  'Coloración Gram',
  'Coloración Wright',
  'Citología de oído para bacterias y hongos (Coloración Gram)',
  'Citología vaginal reproductiva',
  'Citología diagnóstica',
  'PAF BACAF',
  'Tricograma',
  'Raspado de piel (KOH y ácaros)',
  'Raspado piel + KOH + tricograma',
  // Uroanálisis
  'Parcial de orina',
  'UPC',
  // Coprológico
  'Coprológico (flotación y directo)',
  'Coprológico seriado (3 muestras)',
  'Coproscópico',
  // Bioquímica individual
  'Albúmina',
  'Bilirrubina total y directa',
  'BUN Nitrógeno ureico',
  'Calcio',
  'Cloro',
  'Colesterol total',
  'Creatinina',
  'Creatinfosfoquinasa CPK',
  'Fosfatasa alcalina',
  'Fósforo',
  'Gamma glutamil transferasa GGT',
  'Glucosa',
  'Lipasa',
  'Proteínas plasmáticas',
  'Proteínas totales',
  'Proteínas totales y su relación (albúmina, globulina)',
  'Sodio',
  'Transaminasa AST',
  'Transaminasa ALT',
  'Triglicéridos',
  // Perfiles
  'Perfil Básico',
  'Perfil Completo más electrolitos',
  'Perfil Diabético',
  'Perfil gato',
  'Perfil gato adulto',
  'Perfil geriátrico (canino)',
  'Perfil geriátrico (felino)',
  'Perfil hepático sencillo',
  'Perfil hepático completo',
  'Perfil prequirúrgico',
  'Perfil profilaxis',
  'Perfil renal sencillo',
  'Perfil renal más electrolitos',
  // Otro
  'Otro',
];
